/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CyberRouteImport } from './routes/cyber'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as TikaRouteImport } from './routes/tika'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberRoute = CyberRouteImport.update({
  id: '/cyber',
  path: '/cyber',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const TikaRoute = TikaRouteImport.update({
  id: '/tika',
  path: '/tika',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cyber': typeof CyberRoute
  '/navigator': typeof NavigatorRoute
  '/tika': typeof TikaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cyber': typeof CyberRoute
  '/navigator': typeof NavigatorRoute
  '/tika': typeof TikaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cyber': typeof CyberRoute
  '/navigator': typeof NavigatorRoute
  '/tika': typeof TikaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cyber' | '/navigator' | '/tika'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cyber' | '/navigator' | '/tika'
  id: '__root__' | '/' | '/cyber' | '/navigator' | '/tika'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CyberRoute: typeof CyberRoute
  NavigatorRoute: typeof NavigatorRoute
  TikaRoute: typeof TikaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber': {
      id: '/cyber'
      path: '/cyber'
      fullPath: '/cyber'
      preLoaderRoute: typeof CyberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tika': {
      id: '/tika'
      path: '/tika'
      fullPath: '/tika'
      preLoaderRoute: typeof TikaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CyberRoute: CyberRoute,
  NavigatorRoute: NavigatorRoute,
  TikaRoute: TikaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
